/**
 * WebSocket 错误码（与后端 WSErrorCode 保持一致）
 */
export const WSErrorCode = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MESSAGE_EMPTY: 'MESSAGE_EMPTY',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_LOGIN: 'NOT_LOGIN',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
};
